- name: Prepare deployment
  run: |
    mkdir -p _site
    echo "yavuzselimkolbasar.com" > _site/CNAME
    # First copy the root index.html explicitly
    cp ./index.html _site/ || true
    # Then copy the rest of the HTML files with parent directories
    find . -name "*.html" -not -path "./_site/*" -not -path "./node_modules/*" -not -path "./index.html" -exec cp --parents {} _site/ \;
    cp -r css _site/ || true
    cp -r js _site/ || true
    cp -r docs _site/ || true
    cp -r home _site/ || true
    cp -r projects _site/ || true
    cp -r images _site/ || true
    cp -r assets _site/ || true
    cp *.css _site/ || true
    cp *.js _site/ || true
    cp *.svg _site/ || true
    cp LICENSE _site/ || true
    cp README.md _site/ || true
    ls -la _site/
    # Only create a redirect if needed
    if [ ! -f _site/index.html ]; then
      echo '<!DOCTYPE html><html><head><title>Portfolio</title><meta http-equiv="refresh" content="0;url=home/index.html"></head><body>Redirecting to <a href="home/index.html">home page</a>...</body></html>' > _site/index.html
    fi
