name: Deploy static content to Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Prepare deployment
        run: |
          mkdir -p _site
          cp *.html _site/ || true
          cp *.css _site/ || true
          cp *.js _site/ || true
          cp *.svg _site/ || true
          cp -r images _site/ || true
          cp -r assets _site/ || true
          ls -la _site/
          if [ ! -f _site/index.html ]; then
            echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0;url=mainpage"></head><body><script>window.location.href="index.html";</script></body></html>' > _site/index.html
          fi
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
